[workspace]
members = [
    "node",
    # "pallets/assets",
    "pallets/loans",
    # "pallets/loans/lending-rpc/",
    # "pallets/loans/lending-rpc/runtime-api/",
    # "pallets/price_oracle",
    # "pallets/common",
    # "pallets/amm",
    # "runtime"
]
[profile.release]
panic = "unwind"