[workspace]
members = [
    "node",
    "pallets/assets",
    # "pallets/loans",
    # "pallets/price_oracle",
    # "pallets/common"
    "pallets/amm",
    # "runtime",

]
[profile.release]
panic = "unwind"
